version: '2'
services:
  app:
    restart: always
    build: ./app
    command: python bot.py
    ports:
      - "5000:80"
    volumes:
      - ./app:/bot
    depends_on:
      - db

  db:
    restart: always
    image: zsimo/rpi-mongo
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'
